services:
  requester:
    image: fedlang-requester
    container_name: requester
    environment:
      ERL_FLAGS: -setcookie 050df51e-1c75-433e-95c3-8e3e1926d6a6 -name test@172.20.0.254
      FEDLANG_DIRECTOR_NAME: director@172.16.2.185
    volumes:
      - /models:/models
    command: tail -f /dev/null